### ISSUE TITLE
The link is unavailable now !

### ISSUE THREAD

**Issue by yzho0907** [jiyfeng/rl4nlp#2]

**Comment by TomLisankie** [comment]
Which link?

**Comment by yzho0907** [comment]
@TomLisankie Reading: Reinforcement Learning: An Introduction Chap 01 and 03

**Comment by TomLisankie** [comment]
@yzho0907 you're right. Same for all the other readings from that book. @jiyfeng can you please fix?

**Comment by jiyfeng** [comment]
fixed now. Thank you, guys!

**Comment by TomLisankie** [comment]
@jiyfeng The link to the book wasn't updated under sections 2 and 3 of the README, just section 1.
